version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_word_bot
    restart: unless-stopped
    volumes:
      - ./wordlists:/app/wordlists
      - type: bind
        source: ./users.json
        target: /app/users.json
        create_host_path: true
    environment:
      - TZ=UTC
      - BOT_TOKEN=${BOT_TOKEN}