version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_word_bot
    restart: unless-stopped
    volumes:
      - ./wordlists:/app/wordlists
      - ./users.json:/app/users.json
      - ./.env:/app/.env
    environment:
      - TZ=UTC
      - BOT_TOKEN=${BOT_TOKEN}